/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.exercicio2;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JPanel;

/**
 *
 * @author diana
 */
public class CorPanel extends javax.swing.JPanel {

    private JPanel estePanel;
    /**
     * Creates new form CorPanel
     */
    public CorPanel() {
        estePanel = this;
        initComponents();
        txtTexto.setText(fromColorToArrayColor(txtTexto.getForeground()));
        txtFondo.setText(fromColorToArrayColor(txtFondo.getBackground()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        txtTexto = new javax.swing.JTextField();
        txtFondo = new javax.swing.JTextField();
        btnOpenTexto = new javax.swing.JButton();
        btnOpenFondo = new javax.swing.JButton();

        lblTexto.setText("Cor texto:");

        lblFondo.setText("Cor fondo:");
        lblFondo.setToolTipText("");

        txtTexto.setEnabled(false);

        txtFondo.setEnabled(false);

        btnOpenTexto.setText("...");
        btnOpenTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenTextoActionPerformed(evt);
            }
        });

        btnOpenFondo.setText("...");
        btnOpenFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFondoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFondo)
                    .addComponent(lblTexto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTexto)
                    .addComponent(txtFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpenTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTexto)
                    .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenTexto))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFondo)
                    .addComponent(txtFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenFondo))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenTextoActionPerformed

        Color colorSeleccionado = JColorChooser.showDialog(estePanel, "Seleccionar Color", Color.WHITE);

       
        if (colorSeleccionado != null) {
            txtTexto.setText(fromColorToArrayColor(colorSeleccionado));
        }
    }//GEN-LAST:event_btnOpenTextoActionPerformed

    private void btnOpenFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFondoActionPerformed
        Color colorSeleccionado = JColorChooser.showDialog(estePanel, "Seleccionar Color", Color.WHITE);

        if (colorSeleccionado != null) {
            txtFondo.setText(fromColorToArrayColor(colorSeleccionado));
        }
    }//GEN-LAST:event_btnOpenFondoActionPerformed

    public Cor getSelectedValue() {
        Color corTexto = fromArrayColorToColor(txtTexto.getText());
        Color corFondo = fromArrayColorToColor(txtFondo.getText());
        
        
        return new Cor(corTexto, corFondo);
    }
    private Color fromArrayColorToColor(String colorArray) {
        colorArray = colorArray.substring(1, colorArray.length() - 1);

        String[] rgb = colorArray.split(",");


        int r = Integer.parseInt(rgb[0].trim()); 
        int g = Integer.parseInt(rgb[1].trim());
        int b = Integer.parseInt(rgb[2].trim());
 
        return new Color(r, g, b);
    }

    
    private String fromColorToArrayColor(Color color){
        int r = color.getRed();
        int g = color.getGreen();
        int b = color.getBlue();

        StringBuilder sb = new StringBuilder();
        sb.append("[");
        sb.append(String.valueOf(r));
        sb.append(",");
        sb.append(String.valueOf(g));
        sb.append(",");
        sb.append(String.valueOf(b));
        sb.append("]");
        
       
        
        return sb.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenFondo;
    private javax.swing.JButton btnOpenTexto;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JTextField txtFondo;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
